AWSTemplateFormatVersion: "2010-09-09"
Description: "template to provision ec2 instances to install K8s"
Resources:
  DummyServer:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId:  "ami-0dd273d94ed0540c0"
      BlockDeviceMappings:
        - DeviceName: "/dev/sdb"
          Ebs:
            VolumeType: "gp2"
            DeleteOnTermination: "false"
            VolumeSize: "20"
      InstanceType: "t3.medium"
      IamInstanceProfile: "FieldOperationsGovernance"
      SecurityGroupIds:
        - "sg-040889562f1659c13"
      SubnetId: "subnet-097862f7429bc6bc5"
      Tags:
        -
          Key: "resource_owner"
          Value: "arajagopalan"
        -
          Key: "service_name"
          Value: "self-learning"
        -
          Key: "business_unit"
          Value: "FieldOperations"
        -
          Key: "Name"
          Value: !Ref AWS::StackName

      UserData: IyEvYmluL3NoCgpzdWRvIGFwdC1nZXQgdXBkYXRlCnN1ZG8gYXB0LWdldCBpbnN0YWxsIC15IGFwdC10cmFuc3BvcnQtaHR0cHMgY2EtY2VydGlmaWNhdGVzIGN1cmwgZ251cGcgbHNiLXJlbGVhc2UKCiNkb3dubG9hZCBkb2NrZXIgcHVibGljIGtleQpjdXJsIC1mc1NMIGh0dHBzOi8vZG93bmxvYWQuZG9ja2VyLmNvbS9saW51eC91YnVudHUvZ3BnIHwgc3VkbyBncGcgLS1kZWFybW9yIC1vIC91c3Ivc2hhcmUva2V5cmluZ3MvZG9ja2VyLWFyY2hpdmUta2V5cmluZy5ncGcKZWNobyAiZGViIFthcmNoPWFtZDY0IHNpZ25lZC1ieT0vdXNyL3NoYXJlL2tleXJpbmdzL2RvY2tlci1hcmNoaXZlLWtleXJpbmcuZ3BnXSBodHRwczovL2Rvd25sb2FkLmRvY2tlci5jb20vbGludXgvdWJ1bnR1ICQobHNiX3JlbGVhc2UgLWNzKSBzdGFibGUiIHwgc3VkbyB0ZWUgL2V0Yy9hcHQvc291cmNlcy5saXN0LmQvZG9ja2VyLmxpc3QgPiAvZGV2L251bGwKCiNpbnN0YWxsIGRvY2tlcgpzdWRvIGFwdC1nZXQgdXBkYXRlCnN1ZG8gYXB0LWdldCBpbnN0YWxsIC15IGRvY2tlci1jZSBkb2NrZXItY2UtY2xpIGNvbnRhaW5lcmQuaW8KCiNDb25maWd1cmUgdGhlIERvY2tlciBkYWVtb24sIGluIHBhcnRpY3VsYXIgdG8gdXNlIHN5c3RlbWQgZm9yIHRoZSBtYW5hZ2VtZW50IG9mIHRoZSBjb250YWluZXLigJlzIGNncm91cHMKY2F0IDw8RU9GIHwgc3VkbyB0ZWUgL2V0Yy9kb2NrZXIvZGFlbW9uLmpzb24KewogICJleGVjLW9wdHMiOiBbIm5hdGl2ZS5jZ3JvdXBkcml2ZXI9c3lzdGVtZCJdLAogICJsb2ctZHJpdmVyIjogImpzb24tZmlsZSIsCiAgImxvZy1vcHRzIjogewogICAgIm1heC1zaXplIjogIjEwMG0iCiAgfSwKICAic3RvcmFnZS1kcml2ZXIiOiAib3ZlcmxheTIiCn0KRU9GCgojUmVzdGFydCBEb2NrZXIgYW5kIGVuYWJsZSBvbiBib290OgoKc3VkbyAvYmluL3N5c3RlbWN0bCBlbmFibGUgZG9ja2VyCnN1ZG8gL2Jpbi9zeXN0ZW1jdGwgZGFlbW9uLXJlbG9hZApzdWRvIC9iaW4vc3lzdGVtY3RsIHJlc3RhcnQgZG9ja2VyCgoKI0Rvd25sb2FkIHRoZSBHb29nbGUgQ2xvdWQgcHVibGljIHNpZ25pbmcga2V5OgpzdWRvIGN1cmwgLWZzU0xvIC91c3Ivc2hhcmUva2V5cmluZ3Mva3ViZXJuZXRlcy1hcmNoaXZlLWtleXJpbmcuZ3BnIGh0dHBzOi8vcGFja2FnZXMuY2xvdWQuZ29vZ2xlLmNvbS9hcHQvZG9jL2FwdC1rZXkuZ3BnCgojQWRkIHRoZSBLdWJlcm5ldGVzIGFwdCByZXBvc2l0b3J5CmVjaG8gImRlYiBbc2lnbmVkLWJ5PS91c3Ivc2hhcmUva2V5cmluZ3Mva3ViZXJuZXRlcy1hcmNoaXZlLWtleXJpbmcuZ3BnXSBodHRwczovL2FwdC5rdWJlcm5ldGVzLmlvLyBrdWJlcm5ldGVzLXhlbmlhbCBtYWluIiB8IHN1ZG8gdGVlIC9ldGMvYXB0L3NvdXJjZXMubGlzdC5kL2t1YmVybmV0ZXMubGlzdAoKI1VwZGF0ZSBhcHQgcGFja2FnZSBpbmRleCwgaW5zdGFsbCBrdWJlbGV0LCBrdWJlYWRtIGFuZCBrdWJlY3RsLCBhbmQgcGluIHRoZWlyIHZlcnNpb24Kc3VkbyBhcHQtZ2V0IHVwZGF0ZQpzdWRvIGFwdC1nZXQgaW5zdGFsbCAteSBrdWJlbGV0IGt1YmVhZG0ga3ViZWN0bApzdWRvIGFwdC1tYXJrIGhvbGQga3ViZWxldCBrdWJlYWRtIGt1YmVjdGw=

