import asyncio
import aiohttp
import time

appD = {}
errApp = []
errVend = []
appC = 0

startTime = time.time()
fileName = 'async_dc_bug_bounty_1.csv'

appList = ['vshevchenko.favorite-file-notifiler', 'com.enhancera.confaccesslog', 'com.enhancera.jiraaccesslog',
           'de.communardo.confluence.plugins.apc', 'com.intenso.jira.plugins.actions.jsd-actions',
           'com.intenso.jira.plugins.ad-integration-manager', 'com.isostech.ms-jira-activity',
           'ch.mibex.stash.rss4stash', 'com.decadis.xtools-for-jira', 'adobe-xd-jira',
           'eu.asksoftware.bitbucket.advanced-admin-suite', 'confluenceadvancedcodeblockplugin',
           'ch.bitvoodoo.confluence.plugins.panelbox', 'ch.bitvoodoo.confluence.plugins.advanced-search',
           'com.digixperience.atlassian.confluence.spaces-list', 'net.veniture.jira.vAgent',
           'net.bytesource.confluence.agile-blueprint-plugin', 'com.wittified.jira.agile-board-template-builder',
           'de.ancud.jira.plugins.agile-colors', 'net.brokenbuild.agile-estimate',
           'ru.teamlead.jira.plugins.agile-filters-for-jira', 'net.seibertmedia.jira.plugins.agilehive',
           'com.rozdoum.agile-remaining-estimate-counter', 'net.brokenbuild.agile-reports', 'agile.retrospectives',
           'retrospectives4confluence', 'agileretrospectivesjira', 'com.rvs.atlassian.plugins.issuetracer',
           'io.extensi.jira.plugin.agileboardfilter', 'com.bit.agile.bit-storymap', 'net.brokenbuild.velocity-chart',
           'de.ilmcon.jira.protokolle', 'io.aha.confluence.ahaRoadmapsForConfluence', 'io.airfocus.jira',
           'com.synopsys.integration.alert', 'de.kyona.meeting',
           'com.github.sylvainlaurent.gitdescribestashplugin.stash-branch-dashboard', 'io.ally.AllyOKRsForJIRA',
           'com.microfocus.octane.plugins.jira-octane-quality-insight-plugin',
           'com.ila.esolution.jira.jenkinsutils.plugin.jira-jenkins-utils-plugin',
           'com.tse.jira.projects3documents.plugin.jira-project-s3-documents-plugin',
           'org.hotovo.confluence.amazon-s3-storage-connector', 'org.hotovo.jira.amazon-s3-storage-connector-for-jira',
           'com.tse.confluence.spaces3documents.plugin.confluence-space-s3-documents-plugin', 'com.infosysta.jira.JAM',
           'com.nolddor.announcement-banner-for-bitbucket', 'com.nolddor.announcement-banner',
           'com.wittified.atl-announcer-stash', 'com.wittified.atl-announcer-jira', 'de.polygran.jira.fak-issue-sync',
           'de.resolution.apitokenauth.bitbucket', 'com.reinwok.jira.plugins.jira-api-tokens',
           'com.wombatscorp.confluence-tokens', 'com.wombatscorp.jira-tokens',
           'com.intenso.jira.plugins.jira-approvals', 'com.automation-consultants.accloud.approvalmacro',
           'com.arsenalesystems.dataplane', 'com.bilith.lref.confluence-asana', 'asana-jira', 'fi.apio.asciidoc-viewer',
           'com.assertthat.jira.bdd', 'plugin.jip', 'datapluginweb', 'io.ativo.plugins.agile-programs-for-jira',
           'de.edrup.confluence.plugins.attachment-boxes',
           'com.akelesconsulting.confluence.plugins.AttachmentChecker4CONF',
           'com.akelesconsulting.jira.plugins.AttachmentChecker', 'ch.bitvoodoo.confluence.plugins.attachment-tracking',
           'com.enhancera.auditor.confauditor', 'com.plugenta.jiraauditor', 'com.appanvil.aura.aura',
           'com.hivestone.confluence.plugins.autonumberedheadings',
           'com.tse.confluence.purgerecyclebin.plugin.confluence-purge-recyclebin-plugin',
           'com.adaptavist.blocks.autoblocks-jira-server', 'com.gebsun.plugins.jira.startwork',
           'net.seibertmedia.jira.plugins.autopage', 'avono-read-confirmation-plugin',
           'com.amazonaws.services.servicecatalog.connector.jiraservicedesk.jira-servicedesk-connector',
           'azure-devops-confluence-integration', 'com.newverveconsulting.bamboohr',
           'com.tngtech.gadgets.jira-barchart-gadget-plugin', 'com.rocketdev.confluence.barcode',
           'tr.com.obss.plugin.confluence-baseline-plugin', 'com.arijea.plugins.betterblogs',
           'com.midori.bitbucket.plugin.commitpolicy', 'com.midori.confluence.plugin.archiving',
           'com.midori.jira.plugin.excelautomation', 'com.midori.jira.plugin.betterexcel',
           'com.midori.jira.plugin.pdfautomation', 'com.alphaserve.bigquery-connector-jira', 'org.swift.stash.cli',
           'com.rauliki.blockchainviewer.blockchainviewer', 'net.junovi.confluence.blueprint-creator',
           'tig.jira.extension.tigShortcutHeaderExtension', 'com.bilith.lref.confluence-box', 'box-jira',
           'de.viadee.confluence.bpmn-plugin-enterprise', 'com.caseware.stash.branchDetails',
           'com.infosysta.jira.mobile.for.jira.branded', 'com.brikit.blueprintmaker', 'com.brikit.calendars',
           'com.brikit.contentflow', 'com.brikit.targetedsearch', 'com.brikit.themepress',
           'com.lbcg.jira.plugins.bulkclone.BulkClone', 'com.lbcg.jira.plugin.pro.BulkClonePro',
           'com.caritteprod.bulk-linker', 'info.renjithv.jira.plugins.bulkmove.bulkmove-subtasks-jira-plugin',
           'com.kostebekteknoloji.plugins.jira.jira-bulk-operation-exhancer',
           'de.kupper.it.atlassian.confluence.bulk.space.categories', 'uk.co.commercecomputing.users',
           'com.empyra.bud.BulkUserDeleteforJira', 'es.sistel.plugins.jira.bps',
           'com.ctokit.jira.businesstime-jira-plugin', 'org.swift.confluence.cache',
           'ru.teamlead.jira.plugins.JIRA-Teamlead-Calendar', 'com.akelesconsulting.jira.plugins.calendar-heatmap',
           'com.akelesconsulting.jira.plugins.CannedSearchGadget', 'capacity-tracker-plugin',
           'tig.jira.extension.tigCapsuleExtension', 'ru.teamlead.jira.plugins.teamlead-catalog-plugin-for-jira',
           'de.communardo.plugin.stash-project-categories', 'de.kupper.it.atlassian.confluence.categorise.spaces',
           'com.celestecs.confluence.celestecs-conditions', 'com.celestecs.confluence.celestecs-math',
           'com.arsenale.plugins.lockpoint', 'com.plugin.commitgraph.commitgraph', 'es.sistel.plugins.jira.sd-chatbot',
           'jira-cisco-teams-connector', 'net.customware.plugins.connector.salesforce.salesforce-connector-plugin',
           'com.wknowledge.atlassian.confluence.classification.levels', 'com.ros.confluence.cleaner',
           'clockify-timesheets-time-tracking-reports', 'com.cloudbees.sdm.jira',
           'com.easesolutions.jira.plugins.customfields.project-field-manager', 'ch.mibex.bitbucket.codeowners',
           'coinmarketrank.coinmarketrank', 'net.seibertmedia.confluence.collapsable-admin-menu',
           'com.qotilabs.jira.collapsible-dashboard-sidebar-addon', 'ascendintegrated.com.color-cards',
           'com.ascendintegrated.color-queues', 'at.celix.jira.plugins.column-order', 'com.comalatech.checklists',
           'com.comalatech.remotepublishing', 'com.redmoon.jira.commenthistory.commenthistory',
           'com.redmoon.jira.comment-security-default', 'com.kostebekteknoloji.plugins.jira.jira-comment-toolbox',
           'com.bit-booster.graph', 'com.glintech.jira.plugins.compactcards',
           'co.uk.jackgraves.classification.server-classification',
           'com.hivestone.confluence.plugins.conditionalmultiexcerpt',
           'com.tngtech.jira.apps.configuration-cleaner-for-jira', 'com.deniz.jira.versioning',
           'com.botronsoft.jira.configurationmanager',
           'de.devopssystems.confluence.hooks.bitbucket.confluence-hooks-for-bitbucket',
           'ch.bitvoodoo.confluence.plugins.congrats', 'net.customware.confluence.plugin.googledrive',
           'net.customware.confluence.plugin.salesforce.confluence-salesforce-plugin',
           'ch.bitvoodoo.confluence.plugins.contentscheduler', 'com.greenelephant.ci', 'io.kazimir.controlfreak',
           'com.bit-booster.bb.hooks', 'com.hivestone.confluence.plugins.copypagehier',
           'com.akelesconsulting.jira.plugins.Countdown', 'com.akelesconsulting.confluence.plugins.countdown',
           'ru.teamlead.jira.plugins.teamlead-crm-plugin-for-jira',
           'com.mohamicorp.bitbucket.plugin.crucible-review-hook', 'com.empyra.auc.AutoUserCreator',
           'com.olegburmistrov.jira.CurrentProjectFunction',
           'com.tngtech.jira.plugins.customcontent.jira-gadget-custom-content',
           'com.simplenia.confluence.plugins.customdashboards', 'net.seibertmedia.jira.plugins.epic-panel-plugin',
           'mc.customfield.project.administration', 'ch.bitvoodoo.jira.plugins.customfieldsync',
           'com.addonrock.jira.custom-field-pack', 'systems.npe.jira.cfu', 'com.deniz.jira.customfields',
           'com.alphaserve.issuepicker', 'com.kostebekteknoloji.plugins.jira.zephyr-report',
           'raju.kadam.confluence.permissionmgmt', 'com.edagps.atlassian.confluence.custom-toolbar',
           'com.candylio.jira.plugins.jira-csat', 'com.porzelt.jira.darktheme.DarkTheme',
           'com.akelesconsulting.jira.plugins.dFolder', 'com.shdsd.plugin.DueDateReminder',
           'com.atsistemas.confluence.app.awesome-macros', 'tig.jira.extension.tigCommentSecurityExtension',
           'com.gebsun.plugins.jira.defaultvalues', 'com.wittified.delegated-group-management-in-confluence',
           'com.wittified.delegated-group-management-in-jira', 'com.wittified.jira.delegated-admin',
           'com.wittified.jira.project-creator', 'com.wittified.jira.profields.pcfj-integration-with-profields',
           'de.kupper.it.atlassian.confluence.deleteAllAttachments', 'com.hivestone.confluence.plugins.delunusedattach',
           'com.eis.jira.plugins.deletedIssuesLog', 'se.findout.plugin.dependency-map',
           'com.mraddon.descriptiontemplates', 'com.device42.atlas.jira.d42jira',
           'eu.asksoftware.bitbucket.daily-digest-for-bitbucket', 'com.shdsd.plugin.dingding-jira',
           'fr.spectrumgroupe.confluence.plugins.discussion', 'de.viadee.confluence.dmn-plugin',
           'de.viadee.confluence.dmn-plugin-enterprise', 'com.redmoon.jira.documentvault',
           'com.stonikbyte.jira.plugins.project-docs-plugin', 'com.dotuml.confluence',
           'com.accxia.sd.plugins.tailor.tailorman-sd-confirm', 'pl.craftware.jira.download-attachments-plugin',
           'net.seibertmedia.plugin.confluence.duplicate-content-defender',
           'net.veniture.confluence.doublicate_pagetitles', 'com.intenso.jira.plugin.dynamic-forms',
           'doitbetter.matrix', 'net.veniture.confluence.email-this-page', 'eps.focuspro.Translate',
           'eps.focuspro.EasyDropdownMenu', 'cloud.bdq.jsdattachmentemailer',
           'com.jlgdigital.jira.plugin-template-ticket', 'net.artemissoftware.confluence.easyforms.EasyForms',
           'com.binguo.confluence.headingfree.easy-heading-free',
           'com.shineatlas.confluence.headingpro.easy-heading-pro', 'plugin.easyintegration', 'net.koncis.listedit',
           'com.moresimp.epc', 'org.techtime.bitbucket.plugins.easysso', 'org.techtime.confluence.plugins.easysso',
           'org.techtime.jira.plugins.easysso', 'com.appliger.jira.templates',
           'cz.morosystems.atlassian.plugin.easymind', 'nl.avisi.jira.plugins.edit-custom-field-values',
           'com.newverveconsulting.servicedesk.plugins.custom-field-automation',
           'de.edrup.confluence.plugins.edit-inherit', 'com.ovdgroup.jira.EditingRules', 'com.edubrite.atl.gilly-jira',
           'com.tse.confluence.elasticlog.plugin.confluence-elastic-log-plugin',
           'com.tse.jira.elasticlog.plugin.jira-elastic-log-plugin', 'com.sapling.elevator',
           'com.reliex.plugins.email-notifications-digest', 'pl.com.tt.mailtask.MailTask',
           'com.devoog.jira.plugin.encrypted', 'com.tse.jira.issueproperties.plugin.jira-issue-properties-plugin',
           'com.tse.jira.projectproperties.plugin.jira-project-properties-plugin', 'tech.realigned.shareTracker',
           'com.empyra.bpi.BulkProfileImporter', 'plugin.jep', 'com.rauliki.ExportAllIssuesExcel.ExportAllIssuesExcel',
           'com.intenso.confluence.plugins.confluence-password-policy', 'com.intenso.jira.plugins.password-policy',
           'net.getunik.confluence.skin.core', 'com.ijsolutions.jira.epicclonepro.Epic_Clone_Pro',
           'biz.everit.jira.epic-roadmap', 'io.kazimir.epicwatcher', 'ru.teamlead.plugin.jira-plugin-epictime',
           'com.dsplugins.estimator.estimator', 'de.kupper.it.atlassian.confluence.rsvp',
           'pl.com.tt.apdc.excel-365-connector-for-jira', 'pl.com.tt.jira.plugin.excel2jira',
           'com.mobilitystream.jira.excelonline4jiracloud', 'es.excentia.jira.plugins.excentia-admin-tools',
           'tig.jira.extension.tigExportIssuesLiteExtension', 'tig.jira.extension.tigExportIssuesExtension',
           'com.wknowledge.atlassian.confluence.extended-administration',
           'com.itlab.confluence.plugins.restapi-extender', 'com.itlab.jira.plugins.extender',
           'com.ngs.stash.externalhooks.external-hooks', 'ch.bitvoodoo.confluence.plugins.externallinks',
           'fr.spectrumgroupe.confluence.plugins.faq', 'de.actonic.confluence.fus',
           'com.luxplugins.jira.plugin.favorite-issues', 'de.scandio.bitbucket.plugins.favourites',
           'com.plugins4people.jsd.jsd-config-importer', 'io.aety.favfjsd', 'ru.teamlead.jira.plugins.JIRA-Feedback',
           'com.threadq.fh.field_hide', 'com.obss.plugin.fieldSync', 'com.almbase.jira.fieldteller',
           'net.gcore.plugins.fieldtemplates', 'com.apwide.document.file-field', 'com.stiltsoft.bitbucket.fileviewer',
           'com.hivestone.confluence.plugins.findreplace', 'com.activitytimeline.plugins.find-duplicates',
           'com.reinwok.jira.plugins.reinwokcalendar', 'com.reinwok.jira.plugins.jira-reminder', 'kr.osci.apps.flex',
           'kr.osci.apps.flex_jira', 'io.reconquest.bitbucket.labels',
           'com.eis.jira.plugins.gadget.gadgetUtilitiesForJIRA.gadgetUtilitiesForJIRA',
           'app.releasemanagement.releasegadgets.release-gadget', 'ca.nuum.gaia', 'com.brizoit.gantt',
           'de.polscheit.jira.plugins.gantt', 'com.akelesconsulting.jira.plugins.GaugeGadget',
           'de.actonic.confluence.dgpr-tools', 'de.actonic.jira.dgpr-tools', 'net.veniture.jsd.gdpr.JSDPR',
           'com.edubrite.confluence.plugins.gilly', 'nl.avisi.confluence.plugins.git-plugin',
           'de.scandio.confluence.plugins.live-snippets', 'org.tmatesoft.gitx.gitx-bitbucket', 'com.codecanvas.glass',
           'tig.jira.extension.tigGlobalScriptExtension', 'fr.spectrumgroupe.confluence.plugins.glossary',
           'com.wknowledge.atlassian.confluence.wglossary', 'de.kontextwork.goedit.jira', 'de.kontextwork.goedit',
           'google-calendar-confluence', 'com.bilith.lref.confluence-gdrive', 'google-drive-jira',
           'com.elitesoftsp.confluence.google.drive.plugins',
           'com.tse.confluence.googlegroupsync.plugin.confluence-google-group-sync-plugin',
           'com.mobilitystream.jira.google4jiracloud', 'com.infosysta.jira.gtj',
           'com.yworks.plugins.confluence.graphity', 'com.stonikbyte.great.gadgets.server',
           'com.caritteprod.group-ambassadors', 'com.caritteprod.group-ambassadors-conf',
           'de.polscheit.jira.plugins.group-sign-off', 'com.whitesoftware.jira.groupee-group-assignee',
           'com.canerarda.jira.goujql', 'com.seapine.tt.plugins.helix-alm-jira-plugin',
           'com.intenso.jira.plugins.condval.intenso-conditions-validator', 'com.itransition.csam.helpcenter-corrector',
           'helpdesk.helpdesk-for-jira', 'com.vivun.hero.HeroVivun',
           'com.herzum.jira.plugin.approval.herzum-approval-plugin', 'com.gebsun.plugins.jira.hidetimetracking',
           'de.scandio.confluence.plugins.hideelements-macro',
           'info.renjithv.jira.plugins.sysadmin.homedirectorybrowser',
           'ch.bitvoodoo.confluence.plugins.homepageredirect', 'ru.andreymarkelov.atlas.plugins.requestedfields',
           'fr.spectrumgroupe.confluence.plugins.ideation',
           'net.utoolity.atlassian.bitbucket.identity-federation-for-aws-bitbucket',
           'net.utoolity.atlassian.confluence.identity-federation-for-aws-confluence',
           'net.utoolity.atlassian.jira.identity-federation-for-aws-jira', 'com.intrafind.if-pl-confluence',
           'com.intrafind.plugin.confluence.universal-search',
           'com.tse.confluence.scmenthusiastutil.plugin.confluence-scmenthusiast-util-plugin',
           'com.tse.jira.scmenthusiast.util.plugin.jira-scmenthusiast-util-plugin',
           'tig.jira.extension.tigImpersonationExtension', 'com.moresimp.impex',
           'tig.jira.extension.tigSearchbarExtension', 'com.improvekit.rql.rql',
           'com.infosysta.jira.in-app-and-desktop-notifications-for-jira', 'com.inboxforjira.inbox',
           'inline-comments-in-the-editor', 'de.actonic.inline-table-editing',
           'hu.quickprojects.jira.quick-filter-result', 'ZFIN.instantsearch',
           'net.seibertmedia.jira.plugin.instaprinta', 'dropbox-confluence', 'dropbox-jira',
           'se.rixter.jira.restful.integrator.restful_integrator', 'com.botronsoft.jira.rollout.integrity-check',
           'com.clariostechnology.intelligentreports', 'com.djmdesign.intellirest', 'confluence-invisionapp-addon',
           'com.invisionapp.integration.jira', 'com.redmoon.jira.issue-actions-todo',
           'jiraissuecardprinter.jiraissuecardprinter', 'net.gcore.plugins.wgfeedback-marketplace', 'com.aevolu.j.in.c',
           'ru.teamlead.jira.plugins.issue-groups-for-jira', 'com.curvc.atlas.jira.plugin.issuehistory',
           'com.itlab.jira.plugins.issue-linked-event', 'pl.com.tt.apdc.ilv', 'com.botronsoft.jira.issuematrix',
           'com.plugins4people.merge.issue-merge',
           'es.excentia.jira.plugins.jira-issue-picker-custom-field-type-plugin',
           'com.lifeincodes.issue-preview-for-confluence', 'com.lifeincodes.issue-preview-for-jira',
           'com.tngtech.jira.plugins.issueprinter', 'net.veniture.jira.read-indicator', 'com.deniz.jira.reminders',
           'biz.everit.jira.issue-score', 'com.intenso.jira.plugins.synchronizer', 'com.intenso.jira.issue-templates',
           'net.youngaweb.jira.issue-type-ui-filter', 'net.veniture.jira.vMatrix', 'net.veniture.jira.vIssueLayout',
           'com.jbehaveforjira.plugin', 'com.whitesoftware.jira.cmdb-extensions', 'com.minty.minds.atlassian.jira.jcwe',
           'com.jiraeditor.jeditor', 'com.marvelution.jji.automation', 'com.moresimp.jexcel.pro',
           'com.apanasevich.jira-jigit-plugin', 'com.c4f.jira-board', 'com.realtimeboard.plugins.jira_cards',
           'com.lb.software.stash.jira.connector.lb-software-stash-jira-connector', 'com.qmetry.Professional',
           'com.innovalog.jmcf.jira-misc-custom-fields', 'com.langhornweb.jira.app.userexport',
           'com.nolddor.jql-booster-pack', 'com.j-tricks.jql-plugin',
           'com.infosysta.jira.mobile-for-jira-service-desk-portal',
           'com.infosysta.jira.mobile-for-jira-service-desk-portal-branded', 'com.view26.macro.json.viewer.confluence',
           'com.rauliki.kanbancombinedWIP.KanbanCombinedWIP', 'mraddon.hvqzao.jgantt', 'com.kanoah.jira-checklist',
           'com.kanoah.crm', 'com.katalon.katalon-jira-plugin', 'com.keplertechnologies.attachFileCustomField',
           'com.candylio.jira.plugins.jira-kudos', 'ch.bitvoodoo.confluence.plugins.label-fixer',
           'com.kostebekteknoloji.plugins.confluence.confluence-label-manager', 'rs.codecentric.label-manager-project',
           'ch.bitvoodoo.confluence.plugins.labelscheduler', 'net.seibertmedia.confluence.language-manager',
           'com.decadis.confluence.lastlog', 'com.cps.lastLog', 'com.fulstech.confluence-latex',
           'com.fulstech.jira-latex', 'net.leanix.confluence.leanix-for-confluence-server',
           'com.adaptavist.learn.adaptavist-learn', 'de.resolution.user-deactivator.confluence',
           'de.resolution.user-deactivator.bitbucket', 'com.riadalabs.jira.plugins.userdeactivator',
           'net.seibertmedia.confluence.linchpin-essentials', 'net.seibertmedia.confluence.linchpin-suite',
           'net.seibertmedia.confluence.appcenter', 'net.seibertmedia.confluence.plugins.linchpin-theme',
           'net.seibertmedia.plugin.confluence.cup', 'com.hivestone.confluence.plugins.linkreport',
           'com.ovdgroup.jira.linkfields', 'com.otpl.jira.plugins.lxp', 'net.kentcom.live-input-macros',
           'net.bytesource.jira.live-sql-custom-fields-plugin', 'com.intenso.jira.plugin.livechat',
           'de.scandio.confluence.plugins.lively-blog', 'de.scandio.confluence.plugins.lively-theme',
           'es.sistel.plugins.jira.logwork-as-another-user', 'com.reinwok.jira.plugins.log-work-as-user',
           'com.akelesconsulting.jira.plugins.LookupManager', 'com.lucidchart.confluence.plugins.lucid-confluence',
           'com.mabl.jira.server.mabl-jira-server-plugin', 'ch.bitvoodoo.confluence.plugins.macrodescription',
           'org.swift.confluence.macrosecurity', 'de.kupper.it.atlassian.confluence.macro.usage',
           'at.celix.jira.plugins.celix-mail-history', 'net.seibertmedia.confluence.plugin.mailpage',
           'net.gisnas.jira.mailqueue', 'com.tse.confluence.deactivateusers.plugin.confluence-deactivate-users-plugin',
           'com.tse.jira.deactivateusers.plugin.jira-deactivate-users-plugin',
           'com.atlassian.plugins.confluence.markdown.confluence-markdown-macro',
           'com.fulstech.jira-gherkin-custom-field', 'com.i0in.jira.gm.group-mentions',
           'com.akelesconsulting.jira.plugins.relatedFilter', 'com.mergebase.mergebase-vuln-manager',
           'com.fulstech.confluence-graphviz', 'com.jibrok.jira.plugins.message-field',
           'com.osoboo.jira-metadata-plugin', 'net.seibertmedia.plugin.confluence.microblog',
           'com.jsoft.jira.plugins.jira-ms365', 'com.doitbi.bestbi.best-bi', 'com.doitbi.bestbi.powerbi-connector',
           'bitbucket-microsoft-teams-connector', 'net.gcore.plugins.bitbucket2msteams',
           'net.gsolution.plugins.jira-msteams-connector', 'com.realtimeboard.plugins.confluence-server-plugin',
           'eu.mirrorlake.plugins.jira2excel', 'eu.mirrorlake.plugins.mlpc', 'eu.mirrorlake.plugins.pc2d',
           'com.exadel.jira.ml1', 'com.miniorange.rest.auth.confluence-rest-api-oauth',
           'com.miniorange.rest.auth.jira-rest-api-oauth',
           'com.miniorange.git.authentication.bitbucket-git-authentication', 'com.miniorange.sso.saml.bitbucket-sso',
           'com.miniorange.sso.saml.confluence-sso', 'com.miniorange.sso.saml.jira-sso',
           'com.miniorange.usersync.miniorange-usersync-jira', 'com.miniorange.kerberos.confluence-kerberos',
           'com.miniorange.oauth.bitbucket-oauth', 'com.miniorange.oauth.confluence-oauth',
           'com.miniorange.oauth.jira-oauth', 'com.miniorange.bitbucket.crowd.bitbucket-crowd-sso',
           'com.miniorange.confluence.crowd.confluence-crowd-sso', 'com.miniorange.jira.crowd.jira-crowd-sso',
           'com.miniorange.twofactor.bitbucket-twofactor', 'com.miniorange.twofactor.confluence-twofactor',
           'com.miniorange.twofactor.jira-twofactor', 'com.infosysta.jira.mobile', 'com.leanwalk.jirainmotion',
           'net.luethi.plugins.jira.apn4jiraconnect', 'com.mraddon.enchantments.conf.com.mraddon.enchantments.conf',
           'com.mraddon.enchantments.com.mraddon.enchantments', 'com.sourcesense.jira.plugin.cascadingselect',
           'com.cprime.jira.plugins.kb-searcher-jira', 'com.akelesconsulting.jira.plugins.MultipleChartsGadget',
           'com.tngtech.confluence.plugin.multivote',
           'com.tse.confluence.ldapgroupsync.plugin.confluence-ldap-group-sync-plugin',
           'com.ila.esolution.jira.adgroupsync.plugin.jira-ad-group-sync-plugin',
           'com.deviniti.atlassian.apps.extension-myrequests', 'ru.mail.jira.plugins.todolist',
           'com.yassin.plugins.MyUserManagerForJira', 'ru.mail.jira.plugins.mailrucal', 'sk.eea.jira.natural-searchers',
           'com.whitesoftware.jira.navigator-for-jira',
           'com.mraddon.newstatuscolorsconfluence.NewStatusColorsConfluence', 'com.rauliki.NewStatusColors',
           'mraddon.newstatuscolorspro.newstatuscolorspro', 'com.atsistemas.jira.addons.notify-me',
           'com.candylio.jira.plugins.jira-nps', 'com.gtmhub.jira.tasks.tasksPlugin',
           'com.tse.confluence.oktagroupsync.plugin.confluence-okta-group-sync-plugin',
           'com.tse.jira.oktagroupsync.plugin.jira-okta-group-sync-plugin', 'onedrive-confluence', 'onedrive-jira',
           'onepoint.projects.plugin.jira.onepoint-PROJECTS-Connector', 'com.oomnitza.jira.plugin.oomnitza.latest',
           'net.oharagroup.confluence.plugins.confluence-open-api', 'fi.apio.openapi-viewer',
           'com.porzelt.jira.optimize.Optimize', 'co.uk.jackgraves.jira-optimiser', 'com.shdsd.plugin.organizationPro',
           'com.sodius.oslc.app.jira', 'de.mid.oslc-connector-for-jira', 'com.infosysta.plugins.licensing.license',
           'com.akelesconsulting.jira.plugins.OutOfOfficeAssistant', 'de.catworkx.jira.plugins.outlook2jira',
           'expert.marketplace.jira.eclipse.equinox4jira', 'com.shdsd.plugin.attachmentListener',
           'net.customware.confluence.plugin.pageapproval', 'de.scandio.confluence.plugins.page-branching',
           'com.tse.confluence.pageproperties.plugin.confluence-page-properties-plugin',
           'com.tngtech.confluence.plugins.gardening', 'net.kentcom.page-reminders',
           'com.bh.ac.page-templates-tracking', 'net.kentcom.page-view-tracker',
           'com.elitesoftsp.confluence.page.tracking.plugins', 'com.atsistemas.jira.plugins.pageme',
           'com.pagerduty.jira-server-plugin', 'com.simplenia.stash.plugins.pages',
           'de.kupper.it.atlassian.confluence.panels', 'com.kylenicholls.stash.parameterized-builds',
           'de.kupper.it.atlassian.confluence.permission-helper', 'tech.realigned.enhancedDashboards',
           'org.evoja.jira.todoable', 'com.enhancera.pii.pii4conf', 'com.enhancera.pii.pii4jira',
           'com.acidoranges.pincomments.pincomments', 'com.mxgraph.confluence.plugins.plantuml',
           'de.griffel.confluence.plugins.plant-uml', 'de.scandio.confluence.plugins.pocketquery',
           'de.scandio.jira.plugins.pocketquery-jira', 'com.polarnight.polarsso.bitbucket',
           'com.polarnight.polarsso.confluence', 'com.polarnight.polarsso.jira',
           'nl.topicus.bitbucket.bitbucket-webhooks', 'com.botronsoft.jira.poweradmin', 'com.kaanha.jira.powerbi',
           'com.radnorsolutions.collapsable-column-plugin', 'com.mohamicorp.stash.plugin.editor-for-stash',
           'com.bit-booster.bb', 'com.practitest.jira.plugins.practitest-jira-lite', 'de.incloud.confluence.presenter',
           'com.catawiki.jira.prism', 'de.communardo.confluence.communardo.qms.plugin', 'de.proProdukt.prod',
           'de.proProdukt.prod-roles-addon', 'net.solutions.plugins.projectannouncement',
           'com.curvc.atlas.jira.plugin.budget', 'com.redmoon.jira.projectdocuments', 'systems.npe.jira.prjorg',
           'com.stonikbyte.jira.plugins.project-team-plugin', 'com.thepluginpeople.jira.pum',
           'com.prolaborate.macros.prolaborate-macro', 'com.playsql.play-sql-export-addon', 'ch.mibex.bitbucket.pra',
           'com.kurakin.bitbucket.pull-request-review', 'com.greenelephant.pullrequestdependencies',
           'com.tse.confluence.purgepageversions.plugin.confluence-purge-pageversions-plugin',
           'at.celix.jira.plugins.servicedesk-queue-collapse', 'com.infostretch.QmetryTestManager',
           'com.qas.qtest.plugins.jira-plugin', 'com.qasymphony.qtestscenario.version2',
           'com.pti.plugins.qascore.dashboard-gadget', 'quantify-subscription',
           'org.datarocks.atlassian.jira.plugin.quantum', 'ru.mail.jira.plugins.lf.queryfields',
           'com.elitesoftsp.confluence.tiny.question.answer.plugins', 'com.intenso.jira.queues-extension',
           'jh.atlassian.confluence.fliplang.confluence-fliplang', 'jh.atlassian.jira.fliplang.jira-fliplang',
           'com.easesolutions.jira.plugins.requirements', 'com.ros.confluence.rate-me',
           'ru.slie.jira.plugins.customfield', 'com.adaptavist.confluence.rate',
           'com.radbee.confluence.plugins.confluence-training-wizard-core', 'tech.realigned.readConfirmations',
           'com.atsistemas.jira.addons.receive-me', 'com.refinedwiki.confluence.plugins.theme.original',
           'com.refinedwiki.jira.servicedesk.refinedtheme', 'jira-relatedissues-plugin',
           'ru.slie.jira.graty-issue-panel', 'release-management', 'ru.teamlead.jira.plugins.reminder-for-jira',
           'com.codedoers.jira.repeating-issues', 'proficient.developer.plugins.jira.worklog-pivot',
           'net.customware.confluence.plugin.reporting', 'com.kaanha.reports', 'com.shdsd.confluence.plugin.reportWise',
           'fi.apio.archiver', 'ch.mibex.stash.templates', 'com.devsamurai.plugin.jira.team-board',
           'de.kupper.it.atlassian.confluence.carousel', 'de.kupper.it.atlassian.confluence.responsive.image.slider',
           'de.kupper.it.atlassian.confluence.tabs', 'com.ascendintegrated.ribbons',
           'com.qotilabs.jira.rich-filters-plugin', 'com.qotilabs.jira.rich-filters-pdf-reports',
           'com.qotilabs.jira.rich-filters-service-desk-dashboards',
           'com.qotilabs.jira.rich-filters-time-tracking-dashboards', 'com.ja.jira.plugin.report.riskmanagement',
           'com.optimizory.rmsis.plugin.jira-rmsis', 'ru.teamlead.jira.plugins.confluence-language-pack-ru_RU',
           'ru.teamlead.jira.plugins.jirarussianlocal', 'org.swift.confluence.acli', 'org.swift.jira.acli',
           'org.swift.confluence.run', 'net.savignano.s-notify.confluence.gui', 'net.savignano.s-notify.jira.gui',
           'com.atlassian.jira.plugin.customfield.crm', 'eu.toimproveit.saml.bitbucket.SAML4Bitbucket',
           'de.scag.confluence.plugin.eam', 'com.luxplugins.jira.plugin.scim-user-provisioning-for-confluence',
           'com.luxplugins.jira.plugin.scim-user-provisioning',
           'com.tse.jira.scmactivity.plugin.jira-scm-activity-plugin',
           'com.tse.jira.scmactivitylite.plugin.jira-scm-activity-lite-plugin', 'yiraphic.jira.extension.webCapture',
           'org.swift.confluence.script', 'com.k15t.scroll.scroll-html', 'com.k15t.scroll.scroll-translations',
           'com.k15t.scroll.scroll-versions', 'de.codescape.jira.plugins.scrum-poker', 'com.aelbox.scrumpy',
           'org.craftforge.jira.craftforge-jql-functions-plugin', 'net.brutscher.confluence.searchbelow.SearchBelow',
           'net.veniture.confluence.vSearchHighlighter', 'com.redmoon.jira.secure-admin',
           'com.securecodewarrior.jira-integration-prototype', 'com.prcpo.confluence.plugins.secure-content-block',
           'com.coresoftlabs.secure-fields.secure-fields', 'de.syracom.confluence.plugins.securelogin',
           'de.syracom.jira.plugins.securelogin', 'com.mohami.bitbucket.security-for-bitbucket',
           'see-all-unresolved-comments', 'com.pitronote.jira.select2', 'io.reconquest.snake',
           'net.oharagroup.confluence.plugins.confluence-sequence-diagrams', 'software.servado.jira.servado-portals',
           'proficient.developer.plugins.confluence.inline-comments-in-editor', 'com.deniz.jira.similarissues',
           'de.edrup.confluence.plugins.simple-checkout', 'de.edrup.confluence.plugins.simple-cite',
           'com.topshelfsolution.simpletasklists', 'de.edrup.confluence.plugins.simple-anonymizer',
           'org.hotovo.sketch-confluence', 'tig.jira.extension.tigSLALiteExtension',
           'tig.jira.extension.tigSLAExtension', 'com.coresoftlabs.sla_powerbox.sla_powerbox',
           'com.jsoft.jira.plugins.jira-slack', 'com.madein49.slack-for-confluence', 'com.troopr.jira',
           'jira-slack-connector', 'com.pragbits.stash.stash2slack', 'com.troopr.slack_reporting_for_jira',
           'com.troopr.slack-standup-bot', 'de.kupper.it.atlassian.confluence.smart-analytics',
           'com.stiltsoft.confluence.smart-attachment-for-confluence',
           'com.lb.software.stash.smart.commit.lb-software-stash-smart-commit', 'com.mute.confluence.plugins.lms',
           'net.softwaretank.smart-issue-templates', 'com.eis.jira.plugins.jiradoc',
           'de.edrup.confluence.plugins.simple-qa', 'com.mute.confluence.plugins.xTables',
           'com.appsdelivered.smart-user-activity', 'com.smartdraw.confluence.connector',
           'com.smartdraw.jira.connector', 'com.smartdraw.confluence.diagrams', 'com.smartdraw.jira.diagrams',
           'com.forty8fiftylabs.plugins.atlassian.smarthandler_for_mail', 'com.simplenia.stash.plugins.snippets',
           'com.simplenia.confluence.plugins.snippets', 'org.sofmbl.com.Teleport',
           'ee.softcomply.qms.confluence-blueprints', 'ch.mibex.stash.sonar4stash',
           'es.excentia.confluence.plugins.confluence-sonarqube-connector',
           'es.excentia.jira.plugins.jira-sonarqube-connector-plugin', 'com.cognitiff.jira.sortbyanyfield.plugin',
           'com.decadis.confluence.spaceadmin',
           'com.tse.confluence.spaceproperties.plugin.confluence-space-properties-plugin',
           'com.hivestone.confluence.plugins.spacehierarchy', 'net.seibertmedia.extranet.core',
           'com.simplenia.confluence.plugins.spacetree', 'fr.spectrumgroupe.confluence.plugins.formatting.macros',
           'au.net.bunney.spellproof.plugins.spellproof-confluence',
           'com.addonexpertscenter.jira-sprint-planning-resources', 'org.swift.confluence.sql',
           'de.stagil.jira.stagil-assets', 'de.stagil.confluence.stagil-assets-for-confluence',
           'de.stagil.jira.create-and-link', 'de.stagil.jira.stagil-database-sync',
           'de.stagil.jira.stagil-hide-comment', 'de.stagil.silcm.stagil-incoming-links-confluence-macro',
           'de.stagil.confluence.stagil-issues-macro', 'de.stagil.confluence.stagil-lunch-order-confluence',
           'de.stagil.confluence.stagil-navigation-confluence', 'de.stagil.jira.stagil-navigation',
           'de.stagil.jira.password-manager', 'com.stagil.jira.plugins.projects', 'de.stagil.jira.stagil-table-field',
           'de.stagil.jira.stagil-tooltips', 'de.stagil.confluence.stagil-workflows-fields-confluence',
           'com.rauliki.standaloneProjectTemplate.StandaloneProjectTemplate', 'plugin.stateoscope',
           'io.bloompeak.status-time-free', 'tech.realigned.storymappro', 'com.almworks.structure.gantt',
           'com.almworks.structure.pages', 'com.almworks.structure.confluence.helper', 'com.almworks.testy',
           'com.javahollic.confluence.confluencesu', 'com.dolby.atlassian.jira.jirasu', 'net.brokenbuild.subcomponents',
           'com.stiltsoft.bitbucket.submodule', 'ru.teamlead.jira.plugins.subscriptions-for-jira',
           'cz.closeit.atlassian.subtasks-navigation', 'ru.teamlead.jira.plugins.custom-subtasks-section-for-jira',
           'com.suggestimate', 'com.rauliki.JiraSupportAdminTools.JiraSupportAdminTools',
           'com.bitfit.plugins.quick-ticket.jira-server-quick-ticket', 'com.nearinfinity.confluence.survey-plugin',
           'com.unlimax.plugins.confluence.macro.svg.chart.svg-chart-macro-for-confluence',
           'de.edrup.confluence.plugins.svg-out', 'org.tmatesoft.subgit.stash-svn-importer',
           'com.appnovation.jira.synack-integration', 'com.go2group.jira.plugin.synapse', 'ru.slie.jira.sync-fields',
           'com.tngtech.confluence.plugins.tableenhancer', 'com.idalko.jira.plugins.igrid',
           'org.swift.confluence.tablesorter', 'com.kaanha.jira.tableau',
           'com.stiltsoft.confluence.talk.confluence-talk-plugin', 'com.acis.tam', 'ie.mile.task-manager',
           'ie.mile.task-manager-extender', 'de.scandio.confluence.plugins.task-reminder',
           'de.scandio.confluence.plugins.spaceadmin', 'com.stiltsoft.bitbucket.teamcity',
           'ru.teamlead.jira.plugins.teamlead-toolkit', 'de.catworkx.jira.plugins.project-configuration-publisher',
           'de.catworkx.jira.plugins.cwx-issue-picker', 'de.catworkx.jira.plugins.issue-publisher',
           'de.catworkx.jira.apps.cwx-matrix', 'de.catworkx.jira.plugins.push_pull_favorites',
           'net.globosolutions.plugins.bitbucket2telegram', 'net.gsolution.plugins.jira-telegram-connector',
           'com.vilisoft.jira.plugins.template-cloner', 'com.atsistemas.jira.addons.template-me',
           'ch.bitvoodoo.confluence.plugins.blogpost-templates', 'com.greffon.folio',
           'com.glintech.confluence.termsandconditions.termsandconditions',
           'net.seibertmedia.confluence.plugin.termsofuse-plugin', 'com.intenso.jira.plugins.suiTest',
           'com.testrail.jira.testrail-plugin', 'com.thechangecompass.jira-tcc-integration',
           'com.deviniti.atlassian.apps.extension-theme', 'com.adaptavist.confluence.themes.sitebuilder',
           'info.renjithv.jira.addons.threadedcomments.threaded-comments',
           'com.akelesconsulting.jira.plugins.ThreeDDateGadgets', 'com.jibrok.jira.plugins.time-in-status',
           'eu.ducksoft.time-machine', 'timereports', 'com.rozdoum.time-reports-for-remote-jira', 'plugin.tts',
           'com.alphaserve.autoworklog', 'com.mc.jira.gadget.timetracking', 'pl.craftware.jira.cp-timeline-for-jira',
           'com.tda.timesheet.report', 'com.kaanha.timesheets', 'com.shdsd.plugin.DSFineTimesheet', 'com.tinygrc',
           'com.ros.confluence.ToDolist', 'com.kostebekteknoloji.plugins.jira.jira-service-desk-toolbox',
           'com.edagps.atlassian.confluence.tooltip', 'com.edagps.atlassian.confluence.tooltip-pro',
           'com.m20tech.tooltips', 'com.m20tech.tooltips-pro', 'es.excentia.jira.plugins.jira-traceabilityx-plugin',
           'com.adweb.estimations.estimationUpdate', 'de.polscheit.jira.plugins.traffic-light_status',
           'de.ijsolutions.jira.transition-colors.transition-colors', 'com.devoog.jira.plugin.translateFields',
           'com.intenso.jira.plugins.translation.jsd-translation', 'es.excentia.jira.jira-i18n-engine',
           'ch.bitvoodoo.confluence.plugins.language', 'ru.slie.jira.tree-customfield',
           'de.edrup.confluence.plugins.tree-view', 'at.celix.jira.plugins.bamboo-post-function',
           'com.praecipio.jpt.turbo-kit', 'com.snapbytes.jira.plugins.turkishlanguagepack',
           'com.almbase.jira.trlanguagepack', 'com.infosysta.twitter4jira.twitterPlugin', 'com.secsign.secsignid',
           'com.alphaserve.u2fapp', 'fi.apio.ui-tweaks', 'jira-ukrainian-language-pack.biz.softlist.jira.lp',
           'com.prontop.service-desk-landingpage', 'com.prontop.extra-fields-for-jira-service-desk',
           'nl.avisi.jira.plugins.undo-transition-plugin', 'com.jiraworkcalendar.ujg', 'com.ovdgroup.jira.unilistener',
           'ru.teamlead.jira.plugins.teamlead-unread-issues-plugin-for-jira',
           'com.accxia.jira.plugins.workscouncil.WorksCouncil', 'org.swift.jira.cw',
           'mpac.gen.riddlers-athel-for-bamboo-1573187292309', 'mpac.gen.weapon-xis-ingrid-for-crowd-1589382619823',
           'com.sourcesense.jira.plugin.plugins-usage-checker', 'com.ros.confluence.user-group-management',
           'nl.avisi.atlassian.stash.user-directory-api', 'nl.avisi.atlassian.confluence.user-directory-api',
           'nl.avisi.atlassian.user-directory-api', 'org.techtime.bitbucket.plugins.usermanagement',
           'org.techtime.confluence.plugins.usermanagement', 'org.techtime.jira.plugins.usermanagement',
           'com.itlab.jira.plugins.user-picker-avatar', 'de.communardo.confluence.plugins.userprofile',
           'de.communardo.jira.plugins.userprofile', 'com.empyra.upl.UserPropertyListenerforJira',
           'com.nolddor.user-switcher-for-confluence', 'de.resolution.usersync.confluence',
           'de.resolution.usersync.bitbucket', 'de.resolution.usersync.jira', 'pl.com.tt.apdc.vacation-manager',
           'com.tx3.vera.vera3Plugin', 'com.veracode.jira.plugin.synchronize.veracode-jira-flaws-synchronizer',
           'net.collabsoft.plugins.jira.jira-version-sync', 'net.brokenbuild.subversions', 'nexonic.artify.jira',
           'org.swift.confluence.visio', 'com.redmoon.projectwatcher.jira', 'com.rozdoum.watchtower',
           'com.shdsd.plugin.confluenceWatermark', 'com.alphaserve.bitbucket.webauthn',
           'com.alphaserve.confluence.webauthn', 'com.alphaserve.jira.webauthn',
           'com.nerdwin15.stash-stash-webhook-jenkins', 'com.shdsd.plugin.weChat-jira',
           'ru.teamlead.confluence.plugins.werewolf-for-confluence',
           'ru.teamlead.jira.plugins.teamlead-werewolf-for-jira', 'com.acidoranges.addons.who-deleted-my-issues',
           'com.edagps.atlassian.confluence.access.confluenceaccess', 'proficient.developer.plugins.jira.who-is-online',
           'de.kupper.it.atlassian.confluence.widgets', 'com.jiraworkcalendar.work-calendar', 'workboard',
           'com.wobo.jira.server.jira-plugin', 'sk.decoy.java.atlassian.jira.workflow-discovery',
           'com.tng.jira.plugins.workflowenhancer', 'de.codecentric.jira.wes',
           'com.atsistemas.jira.addons.convalpos.workflow-magic-box', 'com.coresoftlabs.jira.workflow-powerbox',
           'com.typezoo.jira.workflowrules', 'com.shdsd.jira.plugin.WorkflowWise', 'hr.e2e.worklog-plugin',
           'com.deniz.jira.worklog', 'com.workpath.jira.plugins.servlet.workpath-jira-servlet-for-goals',
           'com.servicerocket.macondo.workplace-jira-connector', 'com.osf.jira.plugins.jira-workplan-report-plugin',
           'wrike-confluence', 'wrike-jira', 'com.cognitiff.jira.plugins.wsjf.plugin',
           'com.decadis.jira.xchart.xchart-core', 'com.xmatters.xmatters', 'smartesting-yest-jira-cloud-app',
           'com.isroot.stash.plugin.yacc', 'com.thed.zephyr.zapi', 'zendesk_for_jira', 'com.zenuml.confluence-addon',
           'com.adaptavist.tm4c', 'io.zeplin.integration.jira']
# appList = ['vshevchenko.favorite-file-notifiler', 'com.enhancera.confaccesslog']
print(len(appList))

with open(fileName, 'w') as file:
    file.write('appKey, appVendor, appNumDowloads, appTotalUsers, appTotalInstalls')
    file.write('\n')


async def main():
    headers = {'Content-type': 'application/json'}
    async with aiohttp.ClientSession(headers=headers) as session:
        tasks = []
        for app in appList:
            task = asyncio.ensure_future(get_app_details(session, app))
            tasks.append(task)
            all_results = await asyncio.gather(*tasks)
        combined_list = []
        for li in all_results:
            combined_list.extend(li)
        return combined_list


async def get_app_details(session, app):
    print(app)
    appUrl = 'https://marketplace.atlassian.com/rest/2/addons/' + app
    async with session.get(appUrl) as response:
        try:
            result_data = await response.json()
            # print(result_data)
            appD[app] = {}
            vendor_url = 'https://marketplace.atlassian.com' + result_data.get('_links').get('vendor').get('href')
            appD[app] = result_data.get('_embedded').get('distribution')
            async with session.get(vendor_url) as vendor_response:
                try:
                    vendor_result_data = await vendor_response.json()
                    appD[app]['Vendor'] = vendor_result_data.get('name')
                except Exception as err:
                    appD[app]['Vendor'] = 'Unknown'
                    print(f'Unexpected Error in getting vendor details {err}')
                    errVend.append(result_data.get('_links').get('vendor'))
            with open(fileName, 'a') as file:
                file.write("{},{},{},{},{}".format(app,
                                                   appD[app].get('Vendor'),
                                                   appD[app].get('downloads'),
                                                   appD[app].get('totalUsers'),
                                                   appD[app].get('totalInstalls')))
                file.write('\n')
            # print(appD)
        except Exception as err:
            print(f'Unexpected Error - {err}')
            errApp.append(app)
        return appD


response2 = asyncio.get_event_loop().run_until_complete(main())
endTime = time.time() - startTime
print(endTime)
