AWSTemplateFormatVersion: "2010-09-09"
Description: "template to provision ec2 instances to install K8s"
Resources:
  DummyServer:
    Type: "AWS::EC2::Instance"
    Metadata:
      AWS::CloudFormation::Init:
        files:
          /etc/osquery/kolide.enrollment_secret:
            mode: "000644"
            owner: root
            group: root
            content:
              !Sub |
              {{resolve:secretsmanager:arn:aws:secretsmanager:us-east-1:531915269918:secret:OsquerySecretForLinux-0Xwaj5:}}
        commands:
          get_osquery_version:
            command: "OSQUERYVERSION=$(osqueryd --version | grep -Po '[0-9].[0-9].[0-9]*')"
          env_file_for_osquery:
            command:
              'echo "FLAG_FILE="/etc/osquery/osquery.flags"
              CONFIG_FILE="/etc/osquery/osquery.conf"
              LOCAL_PIDFILE="/var/osquery/osqueryd.pidfile"
              PIDFILE="/var/run/osqueryd.pidfile"
              # Custom env vars decorators
              OSQUERY_SERVICE=PracticeDevelopmentTeam
              OSQUERY_ENV=osquery_fieldops
              OSQUERY_SERVICE_VERSION=$OSQUERYVERSION
              OSQUERY_DEPLOYMENT_ID=prod
              " >/etc/sysconfig/osqueryd'

    Properties:
      ImageId:  "ami-0dd273d94ed0540c0"
      BlockDeviceMappings:
        - DeviceName: "/dev/sdb"
          Ebs:
            VolumeType: "gp2"
            DeleteOnTermination: "false"
            VolumeSize: "20"
      InstanceType: "t3.medium"
      IamInstanceProfile: "FieldOperationsGovernance"
      SecurityGroupIds:
        - "sg-040889562f1659c13"
      SubnetId: "subnet-097862f7429bc6bc5"
      Tags:
        -
          Key: "resource_owner"
          Value: "arajagopalan"
        -
          Key: "service_name"
          Value: "self-learning"
        -
          Key: "business_unit"
          Value: "FieldOperations"
        -
          Key: "Name"
          Value: !Ref AWS::StackName

      UserData: !Base64
        'Fn::Join':
          - ''
          - - |
              #!/bin/bash -xe
            - |
              #Install files and packages from Metadata
            - '/opt/aws/bin/cfn-init -v '
            - '         --stack '
            - !Ref 'AWS::StackName'
            - '         --resource WebServerInstance '
            - '         --configsets InstallAndRun '
            - '         --region '
            - !Ref 'AWS::Region'
            - |+



